CXX = g++
CPPFLAGS = -std=c++11 -I../include
LDFLAGS = -lpthread

systimer_test:
	${CXX} ${CPPFLAGS} ${LDFLAGS} ../src/timer.cpp systimer_test.cpp -o $@

delegate_test:
	${CXX} ${CPPFLAGS} ${LDFLAGS} delegate_test.cpp -o $@
